import {useEffect,useId,useLayoutEffect,useRef,useState,type PointerEvent as PE} from 'react';
import {createPortal} from 'react-dom';
import type {EnhancementController} from './ImageEnhancement';
import './insulator-focus.css';
export type FocusPoint={x:number;y:number};
export type InsulatorFocus={adaptive?:boolean;match_surroundings?:boolean;points:FocusPoint[];clarity:number;detail:number;shadows:number;background_dim:number};
export type FocusRegion={id:number;name:string;kind:string;points:FocusPoint[]};
export const newFocus=(points:FocusPoint[],previous?:InsulatorFocus|null):InsulatorFocus=>({clarity:.65,detail:.5,shadows:.25,background_dim:0,...previous,points});
function cornersFor(p:FocusPoint[],w:number,h:number){if(p.length===4){const u={x:(p[1].x-p[0].x)*w,y:(p[1].y-p[0].y)*h},v={x:(p[3].x-p[0].x)*w,y:(p[3].y-p[0].y)*h};if(Math.abs(u.x*v.x+u.y*v.y)<.001*Math.hypot(u.x,u.y)*Math.hypot(v.x,v.y))return p}const b=bounds(p);return box({x:b.left,y:b.top},{x:b.right,y:b.bottom})}
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
const bounds=(p:FocusPoint[])=>({left:Math.min(...p.map(q=>q.x)),right:Math.max(...p.map(q=>q.x)),top:Math.min(...p.map(q=>q.y)),bottom:Math.max(...p.map(q=>q.y))});
const box=(a:FocusPoint,b:FocusPoint)=>[a,{x:b.x,y:a.y},b,{x:a.x,y:b.y}];
function regionPoints(r:FocusRegion,w:number,h:number){let p=r.points;if(r.kind==='rectangle')p=box(p[0],p[1]);else if(r.kind==='circle'){const [a,b]=p,radius=Math.hypot(b.x-a.x,b.y-a.y);p=Array.from({length:32},(_,i)=>({x:a.x+Math.cos(i*Math.PI/16)*radius,y:a.y+Math.sin(i*Math.PI/16)*radius}))}return p.map(q=>({x:clamp(q.x/(w-1)),y:clamp(q.y/(h-1))}))}
export function InsulatorFocusControls({control:c,regions}:{control:EnhancementController;regions:FocusRegion[]}){
 const f=c.settings.focus;
 const slider=(label:string,name:'clarity'|'detail'|'shadows'|'background_dim',max=1)=>f&&<label className="enhanceSlider"><span>{label}<output>{Math.round(f[name]*100)}%</output></span><input aria-label={label} type="range" min="0" max={max} step=".01" value={f[name]} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);c.beginGesture()}} onPointerUp={c.endGesture} onPointerCancel={c.endGesture} onLostPointerCapture={c.endGesture} onChange={e=>c.change({focus:{...f,[name]:Number(e.target.value)}})}/></label>;
 return <div className="insulatorFocusControls"><div className="focusHeading"><strong>Insulator focus</strong><span>DISPLAY ONLY</span></div><p className="enhanceHint">Bring out the insulator’s captured edges and patterns.</p><label className="enhanceSelect">Selection shape<select aria-label="Focus selection shape" value={c.focusMode} onChange={e=>c.setFocusMode(e.target.value as 'box'|'freehand')}><option value="box">Box</option><option value="freehand">Freehand outline</option></select></label><button type="button" className="focusDraw" aria-pressed={c.selectingFocus} onClick={()=>c.setSelectingFocus(!c.selectingFocus)}>{c.selectingFocus?'Cancel selection':f?'Redraw insulator area':'Draw insulator area'}</button>
 {c.selectingFocus&&<p className="focusInstruction">Drag to draw. Release to finish. Escape cancels.</p>}
 {!!regions.length&&<label className="enhanceSelect">Or use a measurement area<select aria-label="Use measurement area for insulator focus" value="" onChange={e=>{const r=regions.find(r=>r.id===Number(e.target.value));if(r){c.change({focus:newFocus(regionPoints(r,c.analysis?.width||640,c.analysis?.height||512),f)});c.setSelectingFocus(false);c.setFocusOutline(true)}}}><option value="">Choose an area…</option>{regions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}
 {f&&<><button type="button" className="focusDraw" onClick={()=>{c.change({focus:{...f,adaptive:true,match_surroundings:true,background_dim:0,clarity:.75,detail:.45,shadows:.2}});c.setSelectingFocus(false);c.setFocusOutline(false)}}>Auto enhance selected insulator</button><label className="enhanceCheck"><input type="checkbox" checked={f.match_surroundings!==false} onChange={e=>c.change({focus:{...f,match_surroundings:e.target.checked,background_dim:e.target.checked?0:f.background_dim}})}/>Match surrounding colors</label><p className="enhanceHint">Preserves the original hue and broad brightness, with a soft transition around the selection.</p><label className="enhanceCheck"><input type="checkbox" checked={!!f.adaptive} onChange={e=>c.change({focus:{...f,adaptive:e.target.checked}})}/>Adapt detail to image noise</label><p className="enhanceHint">Balanced local contrast and gentle edge-preserving noise reduction. Sharpening is reduced when clean detail is limited.</p><div className="focusActions"><button type="button" title={c.focusOutline?"Hide the outline and handles; keep the enhancement":"Show the outline and handles to adjust the area"} onClick={()=>{c.setSelectingFocus(false);c.setFocusOutline(!c.focusOutline)}}>{c.focusOutline?'Deselect':'Edit selection'}</button><button type="button" onClick={()=>c.setFocusCompare(true)}>Inspect close-up</button><button type="button" onClick={()=>{c.change({focus:null});c.setSelectingFocus(false)}}>Delete focus</button></div><p className="enhanceHint">{c.focusOutline?'Drag inside to move. Corner nodes resize; the round node rotates. Deselect hides the outline and keeps your enhancement.':'Selection hidden. Your enhancement is still applied. Choose Edit selection to adjust the area.'}</p>{slider('Insulator clarity','clarity')}{slider('Disc edge detail','detail')}{slider('Lift dark areas','shadows')}{slider('Dim background','background_dim',.8)}<label className="enhanceCheck"><input type="checkbox" checked={c.focusOutline} onChange={e=>c.setFocusOutline(e.target.checked)}/>Show focus outline</label>{c.preview?.focus_info?.warning&&<p className="focusQuality">{c.preview.focus_info.warning}</p>}<p className="enhanceHint">Original files, metadata, and temperature readings are preserved.</p></>}
 </div>
}
export function InsulatorFocusOverlay({control:c}:{control:EnhancementController}){
 const host=useRef<HTMLDivElement>(null),gesture=useRef<{id:number;mode:string;start:FocusPoint;points:FocusPoint[];path:FocusPoint[];w:number;h:number}|null>(null);
 const [draft,setDraft]=useState<FocusPoint[]|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{setDraft(null);gesture.current=null},[c.open,c.selectingFocus]);
 if(!c.open||(!c.selectingFocus&&(!c.settings.focus||!c.focusOutline)))return null;
 const point=(e:PE)=>{const r=host.current!.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width),y:clamp((e.clientY-r.top)/r.height)}};
 const start=(e:PE,mode:string)=>{if(e.button!==0||c.busy)return;e.stopPropagation();e.preventDefault();host.current!.setPointerCapture(e.pointerId);host.current!.focus();const r=host.current!.getBoundingClientRect(),p=point(e);gesture.current={id:e.pointerId,mode,start:p,points:c.settings.focus?.points||[],path:[p],w:r.width,h:r.height};setNotice('');if(mode==='draw')setDraft([p]);else c.beginGesture()};
 const update=(e:PE)=>{const g=gesture.current;if(!g||g.id!==e.pointerId)return;e.stopPropagation();const p=point(e);
 if(g.mode==='draw'){if(c.focusMode==='box')g.path=box(g.start,p);else if(Math.hypot((p.x-g.path.at(-1)!.x)*g.w,(p.y-g.path.at(-1)!.y)*g.h)>2)g.path.push(p);setDraft([...g.path]);return}
 const b=bounds(g.points),cx=(b.left+b.right)/2,cy=(b.top+b.bottom)/2;let next:FocusPoint[];
 if(g.mode==='move'){const dx=Math.max(-b.left,Math.min(1-b.right,p.x-g.start.x)),dy=Math.max(-b.top,Math.min(1-b.bottom,p.y-g.start.y));next=g.points.map(q=>({x:q.x+dx,y:q.y+dy}))}
 else if(g.mode==='rotate'){const a=Math.atan2((p.y-cy)*g.h,(p.x-cx)*g.w)-Math.atan2((g.start.y-cy)*g.h,(g.start.x-cx)*g.w);next=g.points.map(q=>({x:cx+((q.x-cx)*g.w*Math.cos(a)-(q.y-cy)*g.h*Math.sin(a))/g.w,y:cy+((q.x-cx)*g.w*Math.sin(a)+(q.y-cy)*g.h*Math.cos(a))/g.h}))}
 else{const i=Number(g.mode),corners=cornersFor(g.points,g.w,g.h),anchor=corners[(i+2)%4],corner=corners[i],u={x:(corners[(i+1)%4].x-anchor.x)*g.w,y:(corners[(i+1)%4].y-anchor.y)*g.h},v={x:(corners[(i+3)%4].x-anchor.x)*g.w,y:(corners[(i+3)%4].y-anchor.y)*g.h};const project=(q:FocusPoint,axis:FocusPoint)=>((q.x-anchor.x)*g.w*axis.x+(q.y-anchor.y)*g.h*axis.y)/(axis.x*axis.x+axis.y*axis.y),sx=project(p,u)/project(corner,u),sy=project(p,v)/project(corner,v);if(sx<.05||sy<.05)return;next=g.points.map(q=>({x:anchor.x+(project(q,u)*sx*u.x+project(q,v)*sy*v.x)/g.w,y:anchor.y+(project(q,u)*sx*u.y+project(q,v)*sy*v.y)/g.h}))}
 if(next.every(q=>q.x>=0&&q.x<=1&&q.y>=0&&q.y<=1))c.change({focus:newFocus(next,c.settings.focus)});
 };
 const finish=(e:PE)=>{const g=gesture.current;if(!g||g.id!==e.pointerId)return;update(e);gesture.current=null;e.stopPropagation();if(g.mode!=='draw'){c.endGesture();return}setDraft(null);let p=g.path;if(p.length>256){const source=p;p=Array.from({length:256},(_,i)=>source[Math.floor(i*source.length/256)])}if(p.length<3)return;const b=bounds(p);if((b.right-b.left)*g.w<6||(b.bottom-b.top)*g.h<6)return;
 const cross=(a:FocusPoint,b:FocusPoint,d:FocusPoint)=>(b.x-a.x)*(d.y-a.y)-(b.y-a.y)*(d.x-a.x);
 for(let i=0;i<p.length;i++)for(let j=i+2;j<p.length;j++){if(i===0&&j===p.length-1)continue;const a=p[i],b=p[(i+1)%p.length],d=p[j],f=p[(j+1)%p.length];if(cross(a,b,d)*cross(a,b,f)<0&&cross(d,f,a)*cross(d,f,b)<0){setNotice('Trace without crossing the outline.');return}}
 const area=Math.abs(p.reduce((sum,q,i)=>sum+q.x*p[(i+1)%p.length].y-p[(i+1)%p.length].x*q.y,0))/2;if(area<.00001){setNotice('Draw a closed area with more width.');return}
 c.change({focus:newFocus(p,c.settings.focus)});c.setSelectingFocus(false);c.setFocusOutline(true);
 };
 const p=draft||c.settings.focus?.points,b=p?.length?bounds(p):null,pos=(q:FocusPoint)=>({left:`${q.x*100}%`,top:`${q.y*100}%`});
 return <div ref={host} tabIndex={-1} className={`focusOverlay ${c.selectingFocus?'selecting':'editing'}`} aria-label="Insulator focus selection" onPointerDown={e=>{if(c.selectingFocus)start(e,'draw')}} onPointerMove={update} onPointerUp={finish} onPointerCancel={()=>{gesture.current=null;setDraft(null);c.endGesture()}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();gesture.current=null;setDraft(null);c.endGesture();c.setSelectingFocus(false);c.setFocusOutline(false)}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();e.stopPropagation();c.change({focus:null})}else if((e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();e.stopPropagation();if(e.key.toLowerCase()==='y'||e.shiftKey)c.redo();else c.undo()}}}>
 {p&&<svg viewBox="0 0 1000 1000" preserveAspectRatio="none"><polygon onPointerDown={e=>{if(!c.selectingFocus)start(e,'move')}} points={p.map(q=>`${q.x*1000},${q.y*1000}`).join(' ')}/></svg>}
 {!c.selectingFocus&&b&&<>{cornersFor(p!,c.analysis?.width||640,c.analysis?.height||512).map((q,i)=><button key={i} type="button" className="focusNode" style={pos(q)} aria-label={`Resize focus corner ${i+1}`} onPointerDown={e=>start(e,String(i))}/>)}<button type="button" className="focusNode focusRotate" style={{...pos({x:(b.left+b.right)/2,y:b.top}),transform:'translate(-50%,-160%)'}} aria-label="Rotate focus selection" title="Drag to rotate" onPointerDown={e=>start(e,'rotate')}>↻</button></>}
 {(c.selectingFocus||notice)&&<span>{notice||'Trace around the insulator · release to finish'}</span>}
 </div>
}
export function InsulatorCloseUp({control:c}:{control:EnhancementController}){
 const clipId=useId().replace(/:/g,''),[zoom,setZoom]=useState(1),closeRef=useRef<HTMLButtonElement>(null),leftRef=useRef<HTMLDivElement>(null),rightRef=useRef<HTMLDivElement>(null);
 useLayoutEffect(()=>{if(!c.focusCompare)return;for(const p of [leftRef.current,rightRef.current])if(p){p.scrollLeft=(p.scrollWidth-p.clientWidth)/2;p.scrollTop=(p.scrollHeight-p.clientHeight)/2}},[zoom,c.focusCompare]);
 useEffect(()=>{if(!c.focusCompare)return;setZoom(1);const prev=document.activeElement as HTMLElement;closeRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopPropagation();c.setFocusCompare(false)}};window.addEventListener('keydown',key,true);return()=>{window.removeEventListener('keydown',key,true);prev?.focus()}},[c.focusCompare]);
 const f=c.settings.focus;if(!c.focusCompare||!f)return null;const b=bounds(f.points),w=c.preview?.width||c.analysis?.width||640,h=c.preview?.height||c.analysis?.height||512;
 const pane=(title:string,url:string|undefined,ref:typeof leftRef,other:typeof rightRef)=><div className="focusComparePane"><strong>{title}</strong><div ref={ref} className="focusCompareScroll" onScroll={e=>{if(other.current){if(Math.abs(other.current.scrollTop-e.currentTarget.scrollTop)>1)other.current.scrollTop=e.currentTarget.scrollTop;if(Math.abs(other.current.scrollLeft-e.currentTarget.scrollLeft)>1)other.current.scrollLeft=e.currentTarget.scrollLeft}}}><div style={{width:`${zoom*100}%`,height:`${zoom*100}%`}}><svg viewBox={`${b.left*w} ${b.top*h} ${Math.max(1,(b.right-b.left)*w)} ${Math.max(1,(b.bottom-b.top)*h)}`} role="img" aria-label={`${title} insulator close-up`}><defs><clipPath id={`${clipId}-${title}`}><rect x={b.left*w} y={b.top*h} width={(b.right-b.left)*w} height={(b.bottom-b.top)*h}/></clipPath></defs><image href={url} width={w} height={h} preserveAspectRatio="none" clipPath={`url(#${clipId}-${title})`}/></svg></div></div></div>;
 return createPortal(<div className="focusCompareBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)c.setFocusCompare(false)}}><section className="focusCompareDialog" role="dialog" aria-modal="true" aria-label="Insulator close-up comparison" onKeyDown={e=>{if(e.key!=='Tab')return;const buttons=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('button')),first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}><div className="focusCompareHeader"><div><strong>Insulator close-up</strong><span>Same area · original and enhanced</span></div><div className="focusZoom">{[1,2,4].map(v=><button key={v} aria-pressed={v===zoom} onClick={()=>setZoom(v)}>{v===1?'Fit':`${v}×`}</button>)}</div><button ref={closeRef} aria-label="Close insulator comparison" onClick={()=>c.setFocusCompare(false)}>×</button></div><div className="focusCompareImages">{pane('Original',c.originalSrc,leftRef,rightRef)}{pane('Enhanced',c.preview?.preview||c.originalSrc,rightRef,leftRef)}</div><p>{c.processing?'Updating enhanced preview…':'Both views stay aligned. Temperature measurements use the original data.'}</p></section></div>,document.body)
}
